/**
 * Welcome Screen Export API - DOCX Generation
 *
 * Handles server-side DOCX generation for the platform guide export.
 * MD and JSON exports are handled client-side.
 */

import { NextRequest, NextResponse } from 'next/server';
import { generateDocx } from '@/lib/docgen/docx-builder';
import { DEFAULT_BRANDING } from '@/lib/docgen/branding';

export async function POST(req: NextRequest) {
  try {
    const { markdownContent, title } = await req.json();

    if (!markdownContent || typeof markdownContent !== 'string') {
      return NextResponse.json(
        { error: 'Invalid request: markdownContent is required' },
        { status: 400 }
      );
    }

    // Generate DOCX with default branding
    const branding = {
      ...DEFAULT_BRANDING,
      enabled: true,
      organizationName: 'Local AI Assistant',
      primaryColor: '#2563eb', // Blue-600
      header: { enabled: true, content: 'AI Assistant Platform Guide' },
      footer: {
        enabled: true,
        content: 'Generated by Local AI Assistant',
        includePageNumber: true,
      },
    };

    const result = await generateDocx({
      title: title || 'AI Assistant Platform Guide',
      content: markdownContent,
      branding,
      metadata: {
        author: 'Local AI Assistant',
        subject: 'Platform Guide',
        keywords: ['AI', 'Local AI Assistant', 'Services', 'Magic Words'],
        description: 'Comprehensive guide to the AI Assistant Platform',
      },
    });

    // Convert Buffer to Uint8Array for NextResponse compatibility
    const uint8Array = new Uint8Array(result.buffer);

    // Return the DOCX buffer as a downloadable file
    return new NextResponse(uint8Array, {
      headers: {
        'Content-Type':
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': 'attachment; filename="platform-guide.docx"',
        'Content-Length': result.fileSize.toString(),
      },
    });
  } catch (error) {
    console.error('DOCX export error:', error);
    return NextResponse.json(
      { error: 'Failed to generate DOCX document' },
      { status: 500 }
    );
  }
}
